remote_theme: just-the-docs/just-the-docs

# Temel Bilgiler
title: Kyuubi'nin Yeri
url: "https://kyuubi0.github.io"
baseurl: ""

# Eklentileri bu şekilde listele
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

# SASS ayarı
sass:
  style: compressed

# Navigasyon
nav_enabled: true
search_enabled: true