remote_theme: just-the-docs/just-the-docs

title: Kyuubi'nin Yeri
url: "https://kyuubi0.github.io"
baseurl: ""

aux_links:
  "TryHackMe": "https://tryhackme.com/p/kullaniciadin"
  "LinkedIn": "https://linkedin.com/in/kullaniciadin"
  "ArtStation": "https://artstation.com/kullaniciadin"
  "GitHub": "https://github.com/kyuubi0"
  "Itch.io": "https://kullaniciadin.itch.io"

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme