remote_theme: just-the-docs/just-the-docs

title: Kyuubi'nin Yeri
description: Kişisel Portfolyo
url: "https://kyuubi0.github.io"
baseurl: ""

# Arama ve Navigasyon
search_enabled: true
nav_enabled: true

# Bu eklentiler GitHub Pages için zorunludur
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

  sass:
  style: compressed