remote_theme: just-the-docs/just-the-docs

# Temel Bilgiler
title: Kyuubi'nin Yeri
url: "https://kyuubi0.github.io"
baseurl: ""

# CSS ve SASS ayarları
sass:
  style: compressed

# LİNKLER
aux_links:
  "TryHackMe":
    - "https://tryhackme.com/p/kullaniciadin"
  "LinkedIn":
    - "https://www.linkedin.com/in/simge-temel/"
  "ArtStation":
    - "https://www.artstation.com/uftsimge"
  "GitHub":
    - "https://github.com/kyuubi0"
  "Itch.io":
    - "https://uftsimge.itch.io"

aux_links_new_tab: true

# Eklentileri bu şekilde listele
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

# Navigasyon
nav_enabled: true
search_enabled: true

# JavaScript dosyamızı yüklüyoruz
footer_content: '<script src="/assets/js/parallax.js"></script>'